version: '2'
services:
  hackbridge-postgresql:
    image: postgres:12.1
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
    volumes:
      - hackbridge_postgres_data:/var/lib/postgresql/data

volumes:
  hackbridge_postgres_data:
